### ISSUE TITLE
Add support for moving tabs to container

### ISSUE THREAD

**Issue by Keith94** [mikeconley/multi-select-tabs#18]
Refer to "contextual indentities" feature: https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

It would be very useful to move multiple tabs to an existing container. Can it be added?

**Comment by grahamperrin** [comment]
[Moving between containers · mozilla/testpilot-containers Wiki](https://github.com/mozilla/testpilot-containers/wiki/Moving-between-containers)
